model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: masked_image
    image_size: 64
    channels: 3
    concat_mode: true
#    monitor: val/loss
    monitor: val_loss
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 1000
        max_decay_steps: 50000
        lr_start: 0.001
        lr_max: 0.1
        lr_min: 0.0001
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 7
        out_channels: 3
#        model_channels: 256
        model_channels: 224
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
#        monitor: val/rec_loss
        monitor: val_rec_loss
        ckpt_path: /kaggle/input/vq-f4-noattn/model.ckpt
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: ldm.modules.losses.contperceptual.DummyLoss
    cond_stage_config: __is_first_stage__

data:
  target: main.DataModuleFromConfig
  params:
#    batch_size: 48
#    num_workers: 5
    batch_size: 5
    num_workers: 4
    wrap: false
    train:
#      target: taming.data.faceshq.CelebAHQTrain
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /kaggle/working/ldm_thin_t2_test/datasets/celeba-hq-dataset/train_shuffled_Kaggle.flist
        size: 256
        mask_mode: ThinStrokes   # 'hybrid' 'center' 'ThinStrokes',  'MediumStrokes', 'ThickStrokes', 'Every_N_Lines', 'Completion', 'Expand', 'Nearest_Neighbor', m3, m5, m7
    validation:
#      target: taming.data.faceshq.CelebAHQValidation
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /kaggle/working/ldm_thin_t2_test/datasets/celeba-hq-dataset/val_shuffled_Kaggle.flist
        size: 256
        mask_mode: center   # 'hybrid' 'center' 'ThinStrokes',  'MediumStrokes', 'ThickStrokes', 'Every_N_Lines', 'Completion', 'Expand', 'Nearest_Neighbor', m3, m5, m7


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
