model:
  base_learning_rate: 4.5e-06
#  target: ldm.models.autoencoder.VQModel
  target: taming-transformers-master.taming.models.vqgan.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
#    monitor: val/rec_loss
    monitor: val_rec_loss
    ddconfig:
      attn_type: none
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 11
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
#    batch_size: 8
#    num_workers: 12

    batch_size: 3
    num_workers: 3
    wrap: true
    train:
      target: taming-transformers-master.taming.data.custom.CustomTrain
      params:
        training_images_list_file: /home/zwb/zwb/code/0531/test_kaggle/ldm_thin_t2_test/datasets/celeba-hq-dataset/train_shuffled_local.flist
        size: 256
        mask_mode: ThinStrokes   # 'hybrid' 'center' 'ThinStrokes',  'MediumStrokes', 'ThickStrokes', 'Every_N_Lines', 'Completion', 'Expand', 'Nearest_Neighbor', m3, m5, m7
    #        crop_size: 256
    validation:
      target: taming-transformers-master.taming.data.custom.CustomTest
      params:
        test_images_list_file: /home/zwb/zwb/code/0531/test_kaggle/ldm_thin_t2_test/datasets/celeba-hq-dataset/val_shuffled_local.flist
        size: 256
#        crop_size: 256
        mask_mode: center   # 'hybrid' 'center' 'ThinStrokes',  'MediumStrokes', 'ThickStrokes', 'Every_N_Lines', 'Completion', 'Expand', 'Nearest_Neighbor', m3, m5, m7

